# Generated by Django 5.1 on 2024-11-15 19:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outros_prescritores', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_notificacao', models.CharField(blank=True, max_length=6, null=True, verbose_name='Número notificação')),
                ('data_receita', models.DateField(default=django.utils.timezone.now)),
                ('data_dispensacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_cnes', models.CharField(max_length=20)),
                ('farmaceutico_responsavel', models.CharField(max_length=255)),
                ('imagem_logotipo', models.ImageField(upload_to='logotipos/')),
                ('tipo_estabelecimento', models.CharField(choices=[('Farmacia', 'Farmácia'), ('Almoxarifado Central', 'Almoxarifado Central')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descrição da Localização')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificacao', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('psicotropico', models.CharField(blank=True, choices=[('A', 'Lista A'), ('B', 'Lista B'), ('C', 'Lista C')], max_length=1, null=True, verbose_name='Psicotrópico')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('crm', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da mãe')),
                ('cns', models.CharField(max_length=15, unique=True, verbose_name='CNS')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(auto_now_add=True)),
                ('estabelecimento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_destino', to='estoque.estabelecimento')),
                ('estabelecimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_origem', to='estoque.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.estabelecimento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pregao', 'Pregão'), ('ajuste_estoque', 'Ajuste de Estoque'), ('doacao', 'Doação'), ('entrada_ordinaria', 'Entrada Ordinária'), ('saldo_implantacao', 'Saldo de Implantação')], max_length=50, verbose_name='Tipo de Entrada')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data Nota Fiscal')),
                ('data_recebimento', models.DateField(default=datetime.date.today)),
                ('fonte_financiamento', models.CharField(choices=[('municipal', 'Municipal'), ('federal', 'Federal'), ('estadual_federal', 'Estadual + Federal')], default='municipal', max_length=50)),
                ('fornecedor_tipo', models.CharField(choices=[('distribuidora', 'Distribuidora'), ('entidade', 'Entidade')], default='distribuidora', max_length=50)),
                ('tipo_documento', models.CharField(default='Nota Fiscal', max_length=50)),
                ('numero_documento', models.CharField(default='0000', max_length=50, verbose_name='Número do Documento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estabelecimento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.estabelecimento')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='estoque.distribuicao')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='DispensacaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('dispensacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='estoque.dispensacao')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.estoque')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fabricante')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.localizacao', verbose_name='Localização')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheDispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('dispensacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='estoque.dispensacao')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='dispensacao',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.medico', verbose_name='Médico'),
        ),
        migrations.AddField(
            model_name='dispensacao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.paciente'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estabelecimento')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('data_requisicao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Transferida', 'Transferida')], default='Pendente', max_length=20)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('estabelecimento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_destino', to='estoque.estabelecimento')),
                ('estabelecimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_origem', to='estoque.estabelecimento')),
                ('usuario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_aprovadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.requisicao')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_saida', models.CharField(blank=True, max_length=36, unique=True)),
                ('user', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_atendimento', models.DateField()),
                ('status', models.CharField(choices=[('INICIAL', 'Inicial'), ('ATENDIDO', 'Atendido')], default='INICIAL', max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.departamento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.detalhesmedicamento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
    ]
