# Generated by Django 5.1.3 on 2025-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='data',
            field=models.DateField(verbose_name='Data Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='data_recebimento',
            field=models.DateField(),
        ),
    ]
