# Generated by Django 4.2.16 on 2025-04-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='lote',
            field=models.CharField(max_length=50),
        ),
    ]
