# Generated by Django 4.2.16 on 2024-11-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_detalhesmedicamento_estabelecimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuicaomedicamento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_por_lote', to='estoque.detalhesmedicamento'),
        ),
        migrations.AlterField(
            model_name='distribuicaomedicamento',
            name='validade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_por_validade', to='estoque.detalhesmedicamento'),
        ),
    ]
