# Generated by Django 5.1.3 on 2025-03-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_entradaestoque_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='data_recebimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
