# Generated by Django 4.2.16 on 2024-12-06 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_distribuicaomedicamento_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaestoque',
            name='data_atendimento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
