# Generated by Django 4.2.8 on 2024-05-29 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='data_recebimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='fonte_financiamento',
            field=models.CharField(choices=[('municipal', 'Municipal'), ('federal', 'Federal'), ('estadual_federal', 'Estadual + Federal')], default='municipal', max_length=50),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='fornecedor_tipo',
            field=models.CharField(choices=[('distribuidora', 'Distribuidora'), ('entidade', 'Entidade')], default='distribuidora', max_length=50),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='numero_documento',
            field=models.CharField(default='0000', max_length=50),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='tipo_documento',
            field=models.CharField(default='Nota Fiscal', max_length=50),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(max_length=15, unique=True, verbose_name='CNS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(max_length=100, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='registromovimentacao',
            name='tipo',
            field=models.CharField(choices=[('ajuste_estoque', 'Ajuste de Estoque'), ('doacao', 'Doação'), ('entrada_ordinaria', 'Entrada Ordinária'), ('pregao', 'Pregão'), ('saldo_implantacao', 'Saldo de Implantação')], max_length=50),
        ),
        migrations.AddField(
            model_name='registromovimentacao',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.fornecedor'),
        ),
    ]
