# Generated by Django 4.2.16 on 2025-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_entradaestoque_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuicaomedicamento',
            name='validade',
        ),
    ]
