# Generated by Django 4.2.16 on 2025-04-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_remove_distribuicaomedicamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Descrição da Localização'),
        ),
        migrations.CreateModel(
            name='ItemSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.detalhesmedicamento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.saidaestoque')),
            ],
        ),
    ]
