# Generated by Django 5.1.3 on 2024-12-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_saidaestoque_data_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuicaomedicamento',
            name='validade',
        ),
        migrations.AlterField(
            model_name='distribuicaomedicamento',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.detalhesmedicamento'),
        ),
    ]
