# Generated by Django 4.2.16 on 2025-04-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_localizacao_nome_itemsaida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidaestoque',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='saidaestoque',
            name='quantidade',
        ),
    ]
