# Generated by Django 5.1.3 on 2024-12-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_distribuicaomedicamento_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_medicamento', to='estoque.medicamento'),
        ),
    ]
