# Generated by Django 4.2.16 on 2025-04-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_saidaestoque_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicao',
            name='recebido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estoque',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.detalhesmedicamento'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('estabelecimento', 'medicamento', 'lote')},
        ),
    ]
