# Generated by Django 5.1.3 on 2025-01-31 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_estoque_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuicaomedicamento',
            name='validade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_por_validade', to='estoque.detalhesmedicamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='numero_documento',
            field=models.CharField(max_length=50, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='tipo_documento',
            field=models.CharField(choices=[('Nota Fiscal', 'Nota Fiscal'), ('Nota Simples Remessa', 'Nota Simples Remessa'), ('Outro', 'Outro')], default='Nota Fiscal', max_length=50),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total'),
        ),
    ]
