# Generated by Django 4.2.16 on 2025-02-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_distribuicaomedicamento_validade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequisicao',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.detalhesmedicamento'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Processando Transferência', 'Processando Transferência'), ('Transferida', 'Transferida'), ('Rejeitada', 'Rejeitada')], default='Pendente', max_length=30),
        ),
    ]
