# Generated by Django 4.2.17 on 2025-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_itemrequisicao_lote_alter_requisicao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(default='Estante', max_length=100, verbose_name='Descrição da Localização'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
    ]
