# Generated by Django 4.2.8 on 2024-05-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_registromovimentacao_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromovimentacao',
            name='fornecedor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='estoque.fornecedor'),
        ),
    ]
