# Generated by Django 5.1.3 on 2025-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_localizacao_nome_alter_requisicao_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='data_requisicao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
