# Generated by Django 4.2.8 on 2024-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_registromovimentacao_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RegistroMovimentacao',
            new_name='Estoque',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='validade',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='psicotropico',
            field=models.CharField(blank=True, choices=[('A', 'Lista A'), ('B', 'Lista B'), ('C', 'Lista C')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
