# Generated by Django 4.2.8 on 2024-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_medicamento_codigo_identificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='numero_documento',
            field=models.CharField(default='0000', max_length=50, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(max_length=100, verbose_name='Forma farmacêutica'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='psicotropico',
            field=models.CharField(blank=True, choices=[('A', 'Lista A'), ('B', 'Lista B'), ('C', 'Lista C')], max_length=1, null=True, verbose_name='Psicotrópico'),
        ),
    ]
