# Generated by Django 4.2.8 on 2024-06-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_estoque_numero_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhesmedicamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='detalhesmedicamento',
            name='estoque',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_medicamentos', to='estoque.estoque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalhesmedicamento',
            name='medicamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento'),
            preserve_default=False,
        ),
    ]
