# Generated by Django 4.2.8 on 2024-06-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_remove_detalhesmedicamento_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
    ]
