# Generated by Django 3.2.23 on 2024-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_remove_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhesmedicamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo',
            field=models.CharField(choices=[('ajuste_estoque', 'Ajuste de Estoque'), ('doacao', 'Doação'), ('entrada_ordinaria', 'Entrada Ordinária'), ('pregao', 'Pregão'), ('saldo_implantacao', 'Saldo de Implantação')], max_length=50, verbose_name='Tipo de Entrada'),
        ),
    ]
