# Generated by Django 5.0.6 on 2024-06-07 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhesmedicamento',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Nota Fiscal'),
        ),
    ]
