# Generated by Django 4.2.8 on 2024-06-11 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_saida', models.CharField(max_length=8, unique=True)),
                ('operador', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_atendimento', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('INICIAL', 'Inicial'), ('ATENDIDO', 'Atendido')], default='INICIAL', max_length=20)),
                ('lote', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.departamento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
    ]
