# Generated by Django 5.0.6 on 2024-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_saidaestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaestoque',
            name='data_atendimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='saidaestoque',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
