# Generated by Django 5.0.6 on 2024-06-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_alter_saidaestoque_data_atendimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('perfil', models.CharField(max_length=50)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.estabelecimento')),
            ],
        ),
    ]
