# Generated by Django 5.0.6 on 2024-06-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_detalhedispensacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='dosagem',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='forma_farmaceutica',
        ),
    ]
