# Generated by Django 4.2.8 on 2024-07-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_transferenciamedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('farmaceutico', 'Farmacêutico'), ('auxiliar', 'Auxiliar'), ('administrador', 'Administrador')], default='farmaceutico', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='operador',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='operador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='operador',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.perfiloperador'),
        ),
    ]
