# Generated by Django 4.2.8 on 2024-07-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0034_perfiloperador_alter_operador_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiloperador',
            name='perfil',
        ),
        migrations.AddField(
            model_name='perfiloperador',
            name='estabelecimentos',
            field=models.ManyToManyField(related_name='operadores', to='estoque.estabelecimento'),
        ),
        migrations.AddField(
            model_name='perfiloperador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
