# Generated by Django 4.2.8 on 2024-07-02 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0035_remove_perfiloperador_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiloperador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
