# Generated by Django 5.1 on 2024-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0037_funcionalidade_alter_operador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensacao',
            name='numero_notificacao',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Número notificação'),
        ),
    ]
