# Generated by Django 4.2.8 on 2024-10-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0038_alter_dispensacao_numero_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaestoque',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.detalhesmedicamento'),
        ),
    ]
