# Generated by Django 5.0.6 on 2024-10-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0039_alter_saidaestoque_lote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estoque',
            new_name='EntradaEstoque',
        ),
        migrations.AlterField(
            model_name='dispensacao',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.medico', verbose_name='Médico'),
        ),
    ]
