# Generated by Django 5.0.6 on 2024-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0040_rename_estoque_entradaestoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaestoque',
            name='numero_saida',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
