# Generated by Django 4.2.8 on 2024-10-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0041_alter_saidaestoque_numero_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField(auto_now_add=True)),
                ('estabelecimento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_destino', to='estoque.estabelecimento')),
                ('estabelecimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_origem', to='estoque.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('validade', models.DateField()),
                ('distribuicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='estoque.distribuicao')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
            ],
        ),
    ]
