# Generated by Django 4.2.8 on 2024-10-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0042_distribuicao_distribuicaomedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Atendida', 'Atendida')], default='Pendente', max_length=20)),
                ('estabelecimento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_destino', to='estoque.estabelecimento')),
                ('estabelecimento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_origem', to='estoque.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.medicamento')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.requisicao')),
            ],
        ),
    ]
