# Generated by Django 4.2.16 on 2024-10-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0046_requisicao_data_aprovacao_requisicao_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='estabelecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque.estabelecimento'),
        ),
    ]
